In [2]:
import numpy as np

In [15]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the batch size and number of batches we can make
    batch_size = n_seqs * n_steps
    n_batches = int(len(arr)/batch_size)
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches*batch_size]
    
    # Reshape into n_seqs rows
    arr = np.reshape(arr, (n_seqs, -1)) #-1 is the length of each mini sequence
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = arr[:, n+1:n+n_steps+1]
        #y = np.zeros_like(x)
        #y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

In [70]:
class CircArray(np.ndarray):
    pass
    #def __getitem__(self, key):
        #if isinstance(key, int):
            #key = key % self.shape[0]
            
        #return super(CircArray,self).__getitem__(key)
        
a = np.array([1,2,3])
a[:-1]
#print(a[5 % a.shape[0]])
#print(6 % a.shape[0])

array([1, 2])

slice(None, None, None)


In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
n_seqs = 2
n_steps = 3

for x,y in get_batches(arr, n_seqs, n_steps):
    print(x[0])
    print(x)
    print(y)
    print("")

(12,)
[1 2 3]
[[1 2 3]
 [7 8 9]]
[[ 2  3  4]
 [ 8  9 10]]

[4 5 6]
[[ 4  5  6]
 [10 11 12]]
[[ 5  6]
 [11 12]]

